apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlops-artifacts-pvc
  namespace: mlops
  labels:
    app: mlops-fastapi
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard-rwo  # Use GKE's standard-rwo storage class 