apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
        - name: training
          image: cifar10-mlops:stage1
          volumeMounts:
            - name: artifacts
              mountPath: /app/artifacts
      volumes:
        - name: artifacts
          persistentVolumeClaim:
            claimName: artifacts-pvc
